name: Release Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.asset_name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # 允许创建 Release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: minesweep
            asset_name: minesweep-linux-x86_64
          - os: windows-latest
            artifact_name: minesweep.exe
            asset_name: minesweep-windows-x86_64.exe
          - os: macos-latest
            args: "--target x86_64-apple-darwin"
            artifact_name: minesweep
            asset_name: minesweep-macos-x86_64
          - os: macos-latest
            args: "--target aarch64-apple-darwin"
            artifact_name: minesweep
            asset_name: minesweep-macos-aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev pkg-config libssl-dev clang cmake libfontconfig1-dev libxcb1-dev libxkbcommon-x11-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build Release
        run: cargo build --release

      - name: Prepare Artifact (Unix)
        if: runner.os != 'Windows'
        run: |
          mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

      - name: Prepare Artifact (Windows)
        if: runner.os == 'Windows'
        run: |
          mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

      - name: Upload Artifact to Workflow
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/${{ matrix.asset_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/${{ matrix.asset_name }}
